"""add oauth_accounts table

Revision ID: 4427483958ad
Revises: c31969639193
Create Date: 2026-04-01 00:12:32.683339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4427483958ad'
down_revision: Union[str, Sequence[str], None] = 'c31969639193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('oauth_accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_accounts_pkey')),
    sa.UniqueConstraint('platform', 'account_id', name=op.f('oauth_accounts_platform_account_id_key'))
    )
    op.create_index(op.f('ix_oauth_accounts_created_at'), 'oauth_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_deleted_at'), 'oauth_accounts', ['deleted_at'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_oauth_accounts_deleted_at'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_created_at'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
